#!/usr/bin/env bash
# Deployment and Testing Script for Neovim Setup
# Task 14: Deploy to lenovo-21CB001PMX

set -e

echo "=========================================="
echo "STEP 1: Deploying to lenovo-21CB001PMX"
echo "=========================================="
echo ""

# Deploy the configuration
# Note: The flake configuration name is "lenovo" (it points to hosts/lenovo-21CB001PMX/)
sudo nixos-rebuild switch --flake .#lenovo

echo ""
echo "=========================================="
echo "STEP 2: Deployment Complete!"
echo "=========================================="
echo ""
echo "The configuration has been deployed successfully."
echo "Please proceed with manual testing using the checklist below."
echo ""
echo "=========================================="
echo "MANUAL TESTING CHECKLIST"
echo "=========================================="
echo ""
echo "1. Verify Neovim Installation:"
echo "   Run: which nvim"
echo "   Expected: /run/current-system/sw/bin/nvim or similar"
echo ""
echo "   Run: nvim --version"
echo "   Expected: NVIM v0.10.x or later"
echo ""
echo "2. Check Configuration Symlink:"
echo "   Run: ls -la ~/.config/nvim/"
echo "   Expected: Should show init.lua and lua/ directory"
echo ""
echo "3. Launch Neovim and Run Health Check:"
echo "   Run: nvim"
echo "   In Neovim, type: :checkhealth"
echo "   Expected: All core components should be healthy"
echo "            - Treesitter: OK"
echo "            - Telescope: OK"
echo "            - LSP: OK"
echo "            - Git signs: OK"
echo ""
echo "4. Test Treesitter Syntax Highlighting:"
echo "   Run: nvim test-file.nix (or any .nix file)"
echo "   Expected: Syntax highlighting should be visible"
echo "            Code should be colorized properly"
echo ""
echo "5. Test File Explorer:"
echo "   In Neovim, press: Space + e"
echo "   Expected: nvim-tree file explorer should open on the left"
echo "            You should see directory structure"
echo ""
echo "6. Test Fuzzy Finder:"
echo "   In Neovim, press: Space + f + f"
echo "   Expected: Telescope file finder should open"
echo "            You should see a list of files in the project"
echo ""
echo "7. Test Git Signs (if in a git repo):"
echo "   Open a file in a git repository: nvim some-tracked-file"
echo "   Make a change to the file"
echo "   Expected: You should see git signs in the gutter (added/modified/deleted lines)"
echo "            Signs might appear as '+', '~', or '-' symbols"
echo ""
echo "8. Test LSP (Language Server Protocol):"
echo "   Open a Nix file: nvim configuration.nix"
echo "   Hover over a function: Press 'K' in normal mode"
echo "   Expected: Documentation popup should appear (if nil LSP is configured)"
echo ""
echo "9. Additional Keybinding Tests:"
echo "   - Space + f + g : Live grep (search in files)"
echo "   - Space + f + b : Browse buffers"
echo "   - g + d : Go to definition (with LSP)"
echo "   - g + r : Show references (with LSP)"
echo ""
echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "If Neovim is not found:"
echo "  - Check: echo \$PATH"
echo "  - Reload shell: exec \$SHELL"
echo "  - Check home-manager: home-manager generations"
echo ""
echo "If plugins are not loaded:"
echo "  - Check config location: ls -la ~/.config/nvim/"
echo "  - Check for errors: nvim --headless +checkhealth +quit"
echo "  - Review init.lua: cat ~/.config/nvim/init.lua"
echo ""
echo "If Treesitter parsers are missing:"
echo "  - In Neovim: :TSInstallInfo"
echo "  - Check for errors: :messages"
echo ""
echo "=========================================="
echo "DEPLOYMENT COMPLETE - READY FOR TESTING"
echo "=========================================="
